let mapleader = ","

" Set up XDG files
set undodir=$XDG_CACHE_HOME/vim/undo
set directory=$XDG_CACHE_HOME/vim/swap
set backupdir=$XDG_CACHE_HOME/vim/backup
set viewdir=$XDG_DATA_HOME/vim/view
set viminfo+='1000,n$XDG_CACHE_HOME/vim/viminfo
set runtimepath^=$XDG_CONFIG_HOME/vim
set runtimepath+=$XDG_DATA_HOME/vim
set runtimepath+=$XDG_CONFIG_HOME/vim/after
set packpath^=$XDG_DATA_HOME/vim
set packpath+=$XDG_DATA_HOME/vim/after
let g:netrw_home = $XDG_DATA_HOME."/vim"

" Plugins
call plug#begin('$XDG_DATA_HOME/vim/plugged')
Plug 'lervag/vimtex'
call plug#end()

" Enable syntax highlighting
syntax on

" Set text width
set textwidth=79

" Make splits vertically instead of horizontally
set splitbelow splitright

filetype plugin on

" Compile document, be it groff/LaTeX/markdown/etc.
	map <leader>c :w<bar>silent make<bar>redraw!<bar>cw<CR>
" Open corresponding .pdf/.html or preview
	map <leader>p :!opout <c-r>%<CR><CR>

autocmd Filetype nroff setlocal makeprg=/usr/bin/groff\ -ms\ -e\ -Tpdf\ %\ >\ %<.pdf
" TeX specific
autocmd Filetype tex setlocal makeprg=latexmk\ -pdf\ -cd
	\\ -interaction=nonstopmode\ -file-line-error\ %
autocmd Filetype tex setlocal tabstop=2 expandtab shiftwidth=2
autocmd VimLeave *.tex cd %:p:h | !latexmk -c
" C specific
autocmd Filetype c setlocal tabstop=4 expandtab shiftwidth=4 cindent
" Java specific
autocmd Filetype java setlocal tabstop=2 expandtab shiftwidth=2
autocmd Filetype java map <leader>t :w<bar>make! all test<CR>
" html specific
autocmd Filetype html setlocal tabstop=2 expandtab shiftwidth=2

" Quickfix window hightlight is unreadable. Change it!
	hi Search cterm=NONE ctermfg=black ctermbg=yellow


